/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    Accueil: typeof import('./src/components/Accueil.vue')['default']
    Card: typeof import('primevue/card')['default']
    Equipes: typeof import('./src/components/Equipes.vue')['default']
    InfosPratiques: typeof import('./src/components/InfosPratiques.vue')['default']
    Joueurs: typeof import('./src/components/Joueurs.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
